"""Tests for packaged asset installation primitives."""

from __future__ import annotations

from git_stage_batch.data.asset_installation import copy_asset_tree


def test_copy_asset_tree_ignores_python_cache_artifacts(tmp_path):
    """Generated bytecode caches from installed wheels should not be installed."""
    source = tmp_path / "source"
    (source / "__pycache__").mkdir(parents=True)
    (source / "scripts" / "__pycache__").mkdir(parents=True)
    (source / "SKILL.md").write_bytes(b"name: commit-skill\n")
    (source / "__pycache__" / "ignored.cpython-314.pyc").write_bytes(b"cache")
    (source / "scripts" / "helper.py").write_bytes(b"print('ok')\n")
    (source / "scripts" / "helper.pyc").write_bytes(b"cache")
    (source / "scripts" / "helper.pyo").write_bytes(b"cache")
    (source / "scripts" / "__pycache__" / "helper.cpython-314.pyc").write_bytes(b"cache")

    destination = tmp_path / "installed"
    copy_asset_tree(source, destination)

    assert (destination / "SKILL.md").exists()
    assert (destination / "scripts" / "helper.py").exists()
    assert not (destination / "__pycache__").exists()
    assert not (destination / "scripts" / "__pycache__").exists()
    assert not (destination / "scripts" / "helper.pyc").exists()
    assert not (destination / "scripts" / "helper.pyo").exists()
