"""Tests for packaged asset installation primitives."""

from __future__ import annotations

import stat

import pytest

from git_stage_batch.data.asset_installation import (
    copy_asset_tree,
    validate_asset_destination_path,
)
from git_stage_batch.exceptions import CommandError


def test_copy_asset_tree_ignores_python_cache_artifacts(tmp_path):
    """Generated bytecode caches from installed wheels should not be installed."""
    source = tmp_path / "source"
    (source / "__pycache__").mkdir(parents=True)
    (source / "scripts" / "__pycache__").mkdir(parents=True)
    (source / "SKILL.md").write_bytes(b"name: commit-skill\n")
    (source / "__pycache__" / "ignored.cpython-314.pyc").write_bytes(b"cache")
    (source / "scripts" / "helper.py").write_bytes(b"print('ok')\n")
    (source / "scripts" / "helper.pyc").write_bytes(b"cache")
    (source / "scripts" / "helper.pyo").write_bytes(b"cache")
    (source / "scripts" / "__pycache__" / "helper.cpython-314.pyc").write_bytes(b"cache")

    destination = tmp_path / "installed"
    copy_asset_tree(source, destination)

    assert (destination / "SKILL.md").exists()
    assert (destination / "scripts" / "helper.py").exists()
    assert not (destination / "__pycache__").exists()
    assert not (destination / "scripts" / "__pycache__").exists()
    assert not (destination / "scripts" / "helper.pyc").exists()
    assert not (destination / "scripts" / "helper.pyo").exists()


def test_copy_asset_tree_preserves_existing_destination_mode(tmp_path):
    source = tmp_path / "source"
    source.mkdir()
    (source / "asset.txt").write_text("new\n", encoding="utf-8")
    destination = tmp_path / "installed"
    destination.mkdir()
    installed_asset = destination / "asset.txt"
    installed_asset.write_text("old\n", encoding="utf-8")
    installed_asset.chmod(0o755)

    copy_asset_tree(source, destination)

    assert stat.S_IMODE(installed_asset.stat().st_mode) == 0o755


def test_copy_asset_tree_uses_conventional_mode_for_new_files(tmp_path):
    source = tmp_path / "source"
    source.mkdir()
    (source / "asset.txt").write_text("new\n", encoding="utf-8")
    destination = tmp_path / "installed"

    copy_asset_tree(source, destination)

    assert stat.S_IMODE((destination / "asset.txt").stat().st_mode) == 0o644


def test_validate_asset_destination_path_allows_missing_destination(tmp_path):
    """Missing destination paths should be accepted."""
    repo_root = tmp_path / "repo"
    repo_root.mkdir()
    source = tmp_path / "source.txt"
    source.write_text("asset\n", encoding="utf-8")

    validate_asset_destination_path(
        source,
        repo_root / ".codex" / "config.toml",
        repo_root,
    )


def test_validate_asset_destination_path_rejects_blocked_parent(tmp_path):
    """Non-directory parents should block asset installation."""
    repo_root = tmp_path / "repo"
    repo_root.mkdir()
    source = tmp_path / "source.txt"
    source.write_text("asset\n", encoding="utf-8")
    (repo_root / ".codex").write_text("file\n", encoding="utf-8")

    with pytest.raises(
        CommandError,
        match=r"Cannot install bundled assets because '\.codex' is not a directory",
    ):
        validate_asset_destination_path(
            source,
            repo_root / ".codex" / "config.toml",
            repo_root,
        )


def test_validate_asset_destination_path_rejects_file_for_directory_source(tmp_path):
    """File destinations should reject directory assets."""
    repo_root = tmp_path / "repo"
    repo_root.mkdir()
    source = tmp_path / "source"
    source.mkdir()
    destination = repo_root / ".agents"
    destination.write_text("file\n", encoding="utf-8")

    with pytest.raises(
        CommandError,
        match=r"Cannot install bundled assets because '\.agents' is not a directory",
    ):
        validate_asset_destination_path(source, destination, repo_root)


def test_validate_asset_destination_path_rejects_directory_for_file_source(tmp_path):
    """Directory destinations should reject file assets."""
    repo_root = tmp_path / "repo"
    repo_root.mkdir()
    source = tmp_path / "source.txt"
    source.write_text("asset\n", encoding="utf-8")
    destination = repo_root / ".codex"
    destination.mkdir()

    with pytest.raises(
        CommandError,
        match=r"Cannot install bundled assets because '\.codex' is a directory",
    ):
        validate_asset_destination_path(source, destination, repo_root)
